name: Convert Org-mode to PDF

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on new version tags

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs
          sudo apt-get install -y texlive-latex-extra

      - name: Convert Org to PDF
        run: emacs --batch -q --eval '(progn (find-file "workout-plan.org") (org-latex-export-to-pdf))'
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            workout-plan.pdf